### ISSUE TITLE
Support EBS-backed EC2 instances

### ISSUE THREAD

**Issue by thermokarst** [qiime2/vm-playbooks#40]
**Improvement Description**
Many EC2 types are EBS-backed, and having an AMI for that would be pretty great.

**References**
This recently came up on [the forum](https://forum.qiime2.org/t/what-is-the-best-computational-resource/996).

**Comment by jairideout** [comment]
When making this update, include #48.

**Comment by thermokarst** [comment]
This recently[ came up on the forum](https://forum.qiime2.org/t/changing-virtualization-type-on-aws/2400?u=thermokarst).

**Comment by lizgehret** [comment]
No longer building AWS EC2 images, closing.
