### ISSUE TITLE
VirtualBox Version Strategy?

### ISSUE THREAD

**Issue by thermokarst** [qiime2/vm-playbooks#43]
Apparently the latest builds of the QIIME 2 Vbox image [aren't compatible](https://forum.qiime2.org/t/errors-installing-qiime-2-using-virtualbox/1435?u=thermokarst) with the latest VirtualBox. I just checked and I built 2017.9 using VBox 5.1.22 r115126. Moving forward, should we try and use the latest VBox? As well, should we update https://s3-us-west-2.amazonaws.com/qiime2-data/distro/core/virtualbox-images.txt to include the compatible version of VBox?

**Comment by jairideout** [comment]
:+1: for both of your ideas!

**Comment by jairideout** [comment]
I built the 2017.10 image with VirtualBox 5.2.0. The [VirtualBox images file](https://s3-us-west-2.amazonaws.com/qiime2-data/distro/core/virtualbox-images.txt) now has a `Compatible VirtualBox Version` column indicating the version of VirtualBox that the image is known to be compatible with. We know what those versions are for 2017.10 and 2017.9 -- compatibility of older QIIME 2 releases is unknown so those are marked with `?`.

Moving forward, let's build QIIME 2 images with the latest VirtualBox releases, that way users aren't forced to downgrade VirtualBox, and are encouraged to stay up-to-date with the latest VirtualBox and QIIME 2 releases.
