### ISSUE TITLE
Docker: Allow container processes to run as non-root user

### ISSUE THREAD

**Issue by thermokarst** [qiime2/vm-playbooks#49]
This recently [came up on the forum](https://forum.qiime2.org/t/add-non-root-user-capability-for-using-docker-container/1735?u=thermokarst).

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/demux-error-when-following-tutorial-using-docker-image/2667?u=thermokarst).

**Comment by BaconKwan** [comment]
hey, it's really important and useful feature. i can not run it in my multi-user server for now

**Comment by TurbulentCupcake** [comment]
Any progress on this?

**Comment by thermokarst** [comment]
Sorry, no news on this end, @TurbulentCupcake - we would love a helping hand though, if you're interested!

It is worth noting, this Docker image is basically just the conda-based install we recommend to users, tucked into a container (that is, this image doesn't really do anything interesting at the moment that a user or sysadmin couldn't do better, for their own environment).

**Comment by TurbulentCupcake** [comment]
I'm actually one of the users of the compute system referenced in this blog post [here](https://forum.qiime2.org/t/add-non-root-user-capability-for-using-docker-container/1735).

Since compute servers don't typically allow root access to users, trying out the native installation referenced [here](https://docs.qiime2.org/2018.6/install/native/) doesn't work either. I tried the same "native" installation technique on docker but that failed because of the same root-access issue. 

This is probably a long shot but I was looking at [docker-in-docker](https://hub.docker.com/_/docker/), where you can run docker inside another docker, which would contain qiime2. I would imagine that root access for qiime in this case would just be root access to the upper-level docker container instead of the running machine. But I imagine this would be super resource intensive

**Comment by ChristinaLK** [comment]
I've built qiime2 in a Docker container, but have only run it using a shell script external to the container.

**Comment by thermokarst** [comment]
@TurbulentCupcake:

> Since compute servers don't typically allow root access to users, trying out the native installation referenced here doesn't work either. I tried the same "native" installation technique on docker but that failed because of the same root-access issue.

Let's move this part of the discussion over to the [forum](https://forum.qiime2.org) --- there are a few things here that I would to discuss in more detail, but on a more general purpose platform. Thanks!

> This is probably a long shot but I was looking at docker-in-docker, where you can run docker inside another docker, which would contain qiime2. I would imagine that root access for qiime in this case would just be root access to the upper-level docker container instead of the running machine. But I imagine this would be super resource intensive

We have had good luck with docker-in-docker in one of our other projects --- I don't think performance would be an issue. Like I said above though, the docker image, as-is right now, doesn't do anything particularly interesting, so I think it is a matter of just tweaking _how_ qiime2 is installed inside the container to make this work. Stay tuned!

**Comment by ChristinaLK** [comment]
This is the Dockerfile that has worked for me
https://gist.github.com/ChristinaLK/00289f52f54e91a1f8224229afb1b0f8

It's not perfectly seamless because of environment malarkey and I'm too lazy to download all the right ubuntu packages to (say) dl the miniconda installer instead of copying it.

**Comment by thermokarst** [comment]
@ChristinaLK --- this is great - thanks! I actually need to rebuild the 2018.6 VMs ([see this post for motivation](https://forum.qiime2.org/t/incorrect-results-produced-by-q2-quality-control-evaluate-composition/4784?u=nicholas_bokulich)) --- I will carve out an extra hour or so while rebuilding to see if I can integrate the work you just linked to. Stay tuned!

**Comment by thermokarst** [comment]
Okay, I have a pull request open here: https://github.com/qiime2/vm-playbooks/pull/56

My initial tests _appear_ to work, but I need a hand testing this. If I push a test image up to DockerHub, can someone pull it down and test on their system? That would be really helpful! Just let me know if you can and I will push the image and add the pull info here.

Thanks!

**Comment by ChristinaLK** [comment]
I can give it a try.  What image should I be pulling?

**Comment by thermokarst** [comment]
Awesome, thanks @ChristinaLK!

The image can be obtained from here:

```bash
docker pull thermokarst/q2testing
```

Thanks!
